/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProfiles__factory } from "./IProfiles__factory";
export { Profiles__factory } from "./Profiles__factory";
