projects:
  pkdrFinanceUsersApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: nomkehwsuje6tjbbnufvw4nyr4
        maxDepth: 2
extensions:
  amplify:
    version: 3
